import turtle

turtle.hideturtle()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.penup()
turtle.goto(160, 120)
turtle.pendown()
turtle.left(45)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()
turtle.showturtle()

turtle.hideturtle()
turtle.penup()
turtle.goto(80, -120)
turtle.pendown()
turtle.right(90)
turtle.forward(100)
turtle.left(135)
turtle.forward(70)
turtle.left(90)
turtle.forward(70)
turtle.right(157)
turtle.forward(130)
turtle.right(135)
turtle.forward(130)
turtle.left(67)

turtle.penup()
turtle.goto(-180, 180)
turtle.pendown()
turtle.left(45)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.right(135)
turtle.forward(170)
turtle.left(135)

turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)

turtle.penup()
turtle.left(180)
turtle.forward(60)
turtle.right(45)
turtle.pendown()
turtle.forward(85)

turtle.penup()
turtle.right(45)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.right(45)
turtle.pendown()
turtle.forward(85)

turtle.showturtle()
turtle.penup()

turtle.goto(-180, -100)
turtle.right(45)
turtle.pendown()
turtle.write("North")
turtle.forward(90)
turtle.write("South")
turtle.right(180)
turtle.forward(45)
turtle.right(90)
turtle.forward(45)
turtle.write("East")
turtle.right(180)
turtle.forward(90)
turtle.write("West")
turtle.right(180)
turtle.forward(45)
turtle.right(90)
turtle.forward(21)
turtle.left(90)
turtle.circle(20)

turtle.penup()
turtle.goto(-110, -25)
turtle.pendown()
turtle.circle(30)
 
turtle.penup()
turtle.goto(-30, -25)
turtle.pendown()
turtle.circle(30)

turtle.penup()
turtle.goto(50, -25)
turtle.pendown()
turtle.circle(30)
 
turtle.penup()
turtle.goto(-70, -60)
turtle.pendown()
turtle.circle(30)
 
turtle.penup()
turtle.goto(10, -60)
turtle.pendown()
turtle.circle(30)

turtle.penup()
turtle.goto(-70, -80)
turtle.pendown()

turtle.dot()
turtle.forward(5)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(5)

turtle.dot()
turtle.right(90)
turtle.forward(115)

turtle.dot()
turtle.right(90)
turtle.forward(5)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(5)

turtle.dot()
turtle.right(90)
turtle.forward(115)

turtle.hideturtle()
turtle.right(135)
turtle.forward(162)

turtle.left(135)
turtle.forward(115)

turtle.left(135)
turtle.forward(81)
turtle.dot()
turtle.forward(81)


turtle.done()